# Generated by Django 5.0.7 on 2024-12-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
