# Generated by Django 5.0.7 on 2024-12-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.IntegerField()),
                ('option', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
