# Generated by Django 5.0.7 on 2024-12-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
