# Generated by Django 5.0.7 on 2025-09-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_notified',
            field=models.BooleanField(default=False),
        ),
    ]
