# Generated by Django 5.0.7 on 2026-03-07 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_product_low_stock_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('printed_at', models.DateTimeField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='receipt_prints/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='customers.order')),
            ],
            options={
                'ordering': ['-printed_at', '-created'],
            },
        ),
    ]
